configure mutliple nodes in e2e kind cluster
Signed-off-by: FillZpp <FillZpp.pub@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -126,6 +126,7 @@ jobs:
         with:
           node_image: ${{ env.KIND_IMAGE }}
           cluster_name: ${{ env.KIND_CLUSTER_NAME }}
+          config: ./test/kind-conf.yaml
       - name: Setup Kustomize
         uses: imranismail/setup-kustomize@v1
         with:
@@ -140,12 +141,13 @@ jobs:
           set -ex
           kubectl cluster-info
           IMG=openkruise/kruise-manager:e2e-${GITHUB_RUN_ID} ./scripts/deploy_kind.sh
+          NODES=$(kubectl get node | wc -l)
           for ((i=1;i<10;i++));
           do
             set +e
             PODS=$(kubectl get pod -n kruise-system | grep '1/1' | wc -l)
             set -e
-            if [ "$PODS" -eq 2 ]; then
+            if [ "$PODS" -eq "$NODES" ]; then
               break
             fi
             sleep 3
@@ -157,7 +159,7 @@ jobs:
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system --previous=true
           set -e
-          if [ "$PODS" -eq 2 ]; then
+          if [ "$PODS" -eq "$NODES" ]; then
             echo "Wait for kruise-manager and kruise-daemon ready successfully"
           else
             echo "Timeout to wait for kruise-manager and kruise-daemon ready"
@@ -185,6 +187,7 @@ jobs:
         with:
           node_image: ${{ env.KIND_IMAGE }}
           cluster_name: ${{ env.KIND_CLUSTER_NAME }}
+          config: ./test/kind-conf.yaml
       - name: Setup Kustomize
         uses: imranismail/setup-kustomize@v1
         with:
@@ -199,12 +202,13 @@ jobs:
           set -ex
           kubectl cluster-info
           IMG=openkruise/kruise-manager:e2e-${GITHUB_RUN_ID} ./scripts/deploy_kind.sh
+          NODES=$(kubectl get node | wc -l)
           for ((i=1;i<10;i++));
           do
             set +e
             PODS=$(kubectl get pod -n kruise-system | grep '1/1' | wc -l)
             set -e
-            if [ "$PODS" -eq 2 ]; then
+            if [ "$PODS" -eq "$NODES" ]; then
               break
             fi
             sleep 3
@@ -216,7 +220,7 @@ jobs:
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system --previous=true
           set -e
-          if [ "$PODS" -eq 2 ]; then
+          if [ "$PODS" -eq "$NODES" ]; then
             echo "Wait for kruise-manager and kruise-daemon ready successfully"
           else
             echo "Timeout to wait for kruise-manager and kruise-daemon ready"
@@ -244,6 +248,7 @@ jobs:
         with:
           node_image: ${{ env.KIND_IMAGE }}
           cluster_name: ${{ env.KIND_CLUSTER_NAME }}
+          config: ./test/kind-conf.yaml
       - name: Setup Kustomize
         uses: imranismail/setup-kustomize@v1
         with:
@@ -258,12 +263,13 @@ jobs:
           set -ex
           kubectl cluster-info
           IMG=openkruise/kruise-manager:e2e-${GITHUB_RUN_ID} ./scripts/deploy_kind.sh
+          NODES=$(kubectl get node | wc -l)
           for ((i=1;i<10;i++));
           do
             set +e
             PODS=$(kubectl get pod -n kruise-system | grep '1/1' | wc -l)
             set -e
-            if [ "$PODS" -eq 2 ]; then
+            if [ "$PODS" -eq "$NODES" ]; then
               break
             fi
             sleep 3
@@ -275,7 +281,7 @@ jobs:
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system --previous=true
           set -e
-          if [ "$PODS" -eq 2 ]; then
+          if [ "$PODS" -eq "$NODES" ]; then
             echo "Wait for kruise-manager and kruise-daemon ready successfully"
           else
             echo "Timeout to wait for kruise-manager and kruise-daemon ready"
@@ -287,6 +293,67 @@ jobs:
           go install github.com/onsi/ginkgo/ginkgo
           ./scripts/generate_bindata.sh
           ginkgo -timeout 60m -v --focus='\[apps\] DaemonSet' test/e2e
+
+  e2e-tests-for-sidecarset:
+    runs-on: ubuntu-18.04
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          submodules: true
+      - name: Setup Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: ${{ env.GO_VERSION }}
+      - name: Setup Kind Cluster
+        uses: helm/kind-action@v1.2.0
+        with:
+          node_image: ${{ env.KIND_IMAGE }}
+          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
+          config: ./test/kind-conf.yaml
+      - name: Setup Kustomize
+        uses: imranismail/setup-kustomize@v1
+        with:
+          kustomize-version: ${{ env.KUSTOMIZE_VERSION }}
+      - name: Build image
+        run: |
+          export IMAGE="openkruise/kruise-manager:e2e-${GITHUB_RUN_ID}"
+          docker build --pull --no-cache . -t $IMAGE
+          kind load docker-image --name=${KIND_CLUSTER_NAME} $IMAGE || { echo >&2 "kind not installed or error loading image: $IMAGE"; exit 1; }
+      - name: Install Kruise
+        run: |
+          set -ex
+          kubectl cluster-info
+          IMG=openkruise/kruise-manager:e2e-${GITHUB_RUN_ID} ./scripts/deploy_kind.sh
+          NODES=$(kubectl get node | wc -l)
+          for ((i=1;i<10;i++));
+          do
+            set +e
+            PODS=$(kubectl get pod -n kruise-system | grep '1/1' | wc -l)
+            set -e
+            if [ "$PODS" -eq "$NODES" ]; then
+              break
+            fi
+            sleep 3
+          done
+          set +e
+          PODS=$(kubectl get pod -n kruise-system | grep '1/1' | wc -l)
+          kubectl get node -o yaml
+          kubectl get all -n kruise-system -o yaml
+          kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system
+          kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system --previous=true
+          set -e
+          if [ "$PODS" -eq "$NODES" ]; then
+            echo "Wait for kruise-manager and kruise-daemon ready successfully"
+          else
+            echo "Timeout to wait for kruise-manager and kruise-daemon ready"
+            exit 1
+          fi
+      - name: Run E2E Tests
+        run: |
+          export KUBECONFIG=/home/runner/.kube/config
+          go install github.com/onsi/ginkgo/ginkgo
+          ./scripts/generate_bindata.sh
+          ginkgo -timeout 60m -v --focus='\[apps\] sidecarset' test/e2e
 
   e2e-tests-for-other:
     runs-on: ubuntu-18.04
@@ -303,6 +370,7 @@ jobs:
         with:
           node_image: ${{ env.KIND_IMAGE }}
           cluster_name: ${{ env.KIND_CLUSTER_NAME }}
+          config: ./test/kind-conf.yaml
       - name: Setup Kustomize
         uses: imranismail/setup-kustomize@v1
         with:
@@ -317,12 +385,13 @@ jobs:
           set -ex
           kubectl cluster-info
           IMG=openkruise/kruise-manager:e2e-${GITHUB_RUN_ID} ./scripts/deploy_kind.sh
+          NODES=$(kubectl get node | wc -l)
           for ((i=1;i<10;i++));
           do
             set +e
             PODS=$(kubectl get pod -n kruise-system | grep '1/1' | wc -l)
             set -e
-            if [ "$PODS" -eq 2 ]; then
+            if [ "$PODS" -eq "$NODES" ]; then
               break
             fi
             sleep 3
@@ -334,7 +403,7 @@ jobs:
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system
           kubectl get pod -n kruise-system --no-headers | grep daemon | awk '{print $1}' | xargs kubectl logs -n kruise-system --previous=true
           set -e
-          if [ "$PODS" -eq 2 ]; then
+          if [ "$PODS" -eq "$NODES" ]; then
             echo "Wait for kruise-manager and kruise-daemon ready successfully"
           else
             echo "Timeout to wait for kruise-manager and kruise-daemon ready"
@@ -346,7 +415,7 @@ jobs:
           go install github.com/onsi/ginkgo/ginkgo
           ./scripts/generate_bindata.sh
           set +e
-          ginkgo -timeout 60m -v --skip='\[apps\] (StatefulSet|PullImage|ContainerRecreateRequest|DaemonSet)' test/e2e
+          ginkgo -timeout 60m -v --skip='\[apps\] (StatefulSet|PullImage|ContainerRecreateRequest|DaemonSet|sidecarset)' test/e2e
 #          retVal=$?
 #          if [ $retVal -ne 0 ]; then
 #            kubectl get pod -n kruise-system -o wide
